// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/driver_model.dart';
import 'models/driver_work_model.dart';
import 'models/expense_model.dart';
import 'models/farmer_product_model.dart';
import 'models/shop_type_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 6011431848348145895),
      name: 'Driver',
      lastPropertyId: const obx_int.IdUid(9, 6544566588758275281),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 843042492223650522),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 1953520220326855446),
            name: 'd_id_farmer',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 4680305546118733652),
            name: 'id_farmer_user',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 4145546634870284421),
            name: 'id_add_user',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 3660333072529109750),
            name: 'code_farmer',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 2508553881353362368),
            name: 'd_name_farmer',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 7386157252305566179),
            name: 'd_phone_farmer',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 6769447453442368752),
            name: 'add_date',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 6544566588758275281),
            name: 'is_synced',
            type: 1,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 3217152393254578107),
      name: 'DriverWork',
      lastPropertyId: const obx_int.IdUid(12, 2947768461809220202),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6348626614579411928),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 1368499571682815064),
            name: 'd_id_farmer',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 5880002963786994677),
            name: 'd_name_farmer',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 7141777297708792007),
            name: 'type_work',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 5462838061972681903),
            name: 'name_place_work',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 8641529118692658956),
            name: 'time_work_hours',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 4863202685637082956),
            name: 'time_work_minutes',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 7467318595134002013),
            name: 'count_work',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 4994519985662439331),
            name: 'price_work',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 6076323987982330971),
            name: 'pay_type_work',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 4417080134643692582),
            name: 'is_synced',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 2947768461809220202),
            name: 'w_id_driver',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 8025093690978503663),
      name: 'ExpenseModel',
      lastPropertyId: const obx_int.IdUid(13, 2650059496837163130),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8571961319613263515),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 1270350371748072355),
            name: 'id_expense',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 7081840676499252734),
            name: 'id_add_user',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 5033212861477149072),
            name: 'id_farmer_user',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 3977781439080151155),
            name: 'name_farmer',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 5300259025357803891),
            name: 'code_farmer',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 7678022631641798808),
            name: 'name_expense',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 492969600741450051),
            name: 'amount_expense',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 4729635256326983362),
            name: 'e_pay_type',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 6683721045701570749),
            name: 'total_expense_qarz',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 6572804604478197439),
            name: 'total_expense_draw',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 7729692480697024230),
            name: 'is_synced',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 2650059496837163130),
            name: 'add_date',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(4, 8775066774088497496),
      name: 'FarmerProductModel',
      lastPropertyId: const obx_int.IdUid(18, 652309075395766222),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 1652471723994438624),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7960205942659410803),
            name: 'id_product',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 1047765015110787665),
            name: 'id_farmer_user',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 6591771134005937978),
            name: 'id_add_user',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 8702682784001373789),
            name: 'code_farmer',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 2858577960157384736),
            name: 'name_shop',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 6003960049460974137),
            name: 'name_product',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 141217302417224203),
            name: 'number_product',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 1478419719604793710),
            name: 'price_product',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 6739889548717009922),
            name: 'total_amount',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 8360081487425623087),
            name: 'p_pay_type',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 841553286288324757),
            name: 'p_many_type',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 7716899050276826723),
            name: 'total_amount_draw_iq',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 3922186254664419785),
            name: 'total_amount_draw_dolar',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(15, 3739204040707410133),
            name: 'total_amount_qarz_iq',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(16, 6256656884532461943),
            name: 'total_amount_qarz_dolar',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(17, 8400187771020528926),
            name: 'is_synced',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(18, 652309075395766222),
            name: 'add_date',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(5, 8220241113557856762),
      name: 'ShopTypeModel',
      lastPropertyId: const obx_int.IdUid(5, 3201275574212648028),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4862187635594741294),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 4596676678311218852),
            name: 't_id_type',
            type: 6,
            flags: 40,
            indexId: const obx_int.IdUid(1, 2383991197984242339)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 1737400440269047575),
            name: 't_id_farmer',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 5907312991487666985),
            name: 't_name_type',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 3201275574212648028),
            name: 'is_synced',
            type: 1,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(5, 8220241113557856762),
      lastIndexId: const obx_int.IdUid(1, 2383991197984242339),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    Driver: obx_int.EntityDefinition<Driver>(
        model: _entities[0],
        toOneRelations: (Driver object) => [],
        toManyRelations: (Driver object) => {},
        getId: (Driver object) => object.id,
        setId: (Driver object, int id) {
          object.id = id;
        },
        objectToFB: (Driver object, fb.Builder fbb) {
          final code_farmerOffset = object.code_farmer == null
              ? null
              : fbb.writeString(object.code_farmer!);
          final d_name_farmerOffset = object.d_name_farmer == null
              ? null
              : fbb.writeString(object.d_name_farmer!);
          final d_phone_farmerOffset = object.d_phone_farmer == null
              ? null
              : fbb.writeString(object.d_phone_farmer!);
          final add_dateOffset = object.add_date == null
              ? null
              : fbb.writeString(object.add_date!);
          fbb.startTable(10);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.d_id_farmer);
          fbb.addInt64(2, object.id_farmer_user);
          fbb.addInt64(3, object.id_add_user);
          fbb.addOffset(4, code_farmerOffset);
          fbb.addOffset(5, d_name_farmerOffset);
          fbb.addOffset(6, d_phone_farmerOffset);
          fbb.addOffset(7, add_dateOffset);
          fbb.addBool(8, object.is_synced);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final d_id_farmerParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 6);
          final id_farmer_userParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 8);
          final id_add_userParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 10);
          final code_farmerParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12);
          final d_name_farmerParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 14);
          final d_phone_farmerParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 16);
          final add_dateParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 18);
          final is_syncedParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 20, false);
          final object = Driver(
              id: idParam,
              d_id_farmer: d_id_farmerParam,
              id_farmer_user: id_farmer_userParam,
              id_add_user: id_add_userParam,
              code_farmer: code_farmerParam,
              d_name_farmer: d_name_farmerParam,
              d_phone_farmer: d_phone_farmerParam,
              add_date: add_dateParam,
              is_synced: is_syncedParam);

          return object;
        }),
    DriverWork: obx_int.EntityDefinition<DriverWork>(
        model: _entities[1],
        toOneRelations: (DriverWork object) => [],
        toManyRelations: (DriverWork object) => {},
        getId: (DriverWork object) => object.id,
        setId: (DriverWork object, int id) {
          object.id = id;
        },
        objectToFB: (DriverWork object, fb.Builder fbb) {
          final d_name_farmerOffset = object.d_name_farmer == null
              ? null
              : fbb.writeString(object.d_name_farmer!);
          final type_workOffset = object.type_work == null
              ? null
              : fbb.writeString(object.type_work!);
          final name_place_workOffset = object.name_place_work == null
              ? null
              : fbb.writeString(object.name_place_work!);
          final time_work_hoursOffset = object.time_work_hours == null
              ? null
              : fbb.writeString(object.time_work_hours!);
          final time_work_minutesOffset = object.time_work_minutes == null
              ? null
              : fbb.writeString(object.time_work_minutes!);
          final count_workOffset = object.count_work == null
              ? null
              : fbb.writeString(object.count_work!);
          final price_workOffset = object.price_work == null
              ? null
              : fbb.writeString(object.price_work!);
          final pay_type_workOffset = object.pay_type_work == null
              ? null
              : fbb.writeString(object.pay_type_work!);
          fbb.startTable(13);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.d_id_farmer);
          fbb.addOffset(2, d_name_farmerOffset);
          fbb.addOffset(3, type_workOffset);
          fbb.addOffset(4, name_place_workOffset);
          fbb.addOffset(5, time_work_hoursOffset);
          fbb.addOffset(6, time_work_minutesOffset);
          fbb.addOffset(7, count_workOffset);
          fbb.addOffset(8, price_workOffset);
          fbb.addOffset(9, pay_type_workOffset);
          fbb.addBool(10, object.is_synced);
          fbb.addInt64(11, object.w_id_driver);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final w_id_driverParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 26);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final d_id_farmerParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 6);
          final d_name_farmerParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 8);
          final type_workParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final name_place_workParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12);
          final time_work_hoursParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 14);
          final time_work_minutesParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 16);
          final count_workParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 18);
          final price_workParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 20);
          final pay_type_workParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 22);
          final is_syncedParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 24, false);
          final object = DriverWork(
              w_id_driver: w_id_driverParam,
              id: idParam,
              d_id_farmer: d_id_farmerParam,
              d_name_farmer: d_name_farmerParam,
              type_work: type_workParam,
              name_place_work: name_place_workParam,
              time_work_hours: time_work_hoursParam,
              time_work_minutes: time_work_minutesParam,
              count_work: count_workParam,
              price_work: price_workParam,
              pay_type_work: pay_type_workParam,
              is_synced: is_syncedParam);

          return object;
        }),
    ExpenseModel: obx_int.EntityDefinition<ExpenseModel>(
        model: _entities[2],
        toOneRelations: (ExpenseModel object) => [],
        toManyRelations: (ExpenseModel object) => {},
        getId: (ExpenseModel object) => object.id,
        setId: (ExpenseModel object, int id) {
          object.id = id;
        },
        objectToFB: (ExpenseModel object, fb.Builder fbb) {
          final name_farmerOffset = object.name_farmer == null
              ? null
              : fbb.writeString(object.name_farmer!);
          final code_farmerOffset = object.code_farmer == null
              ? null
              : fbb.writeString(object.code_farmer!);
          final name_expenseOffset = object.name_expense == null
              ? null
              : fbb.writeString(object.name_expense!);
          final amount_expenseOffset = object.amount_expense == null
              ? null
              : fbb.writeString(object.amount_expense!);
          final e_pay_typeOffset = object.e_pay_type == null
              ? null
              : fbb.writeString(object.e_pay_type!);
          final total_expense_qarzOffset = object.total_expense_qarz == null
              ? null
              : fbb.writeString(object.total_expense_qarz!);
          final total_expense_drawOffset = object.total_expense_draw == null
              ? null
              : fbb.writeString(object.total_expense_draw!);
          fbb.startTable(14);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.id_expense);
          fbb.addInt64(2, object.id_add_user);
          fbb.addInt64(3, object.id_farmer_user);
          fbb.addOffset(4, name_farmerOffset);
          fbb.addOffset(5, code_farmerOffset);
          fbb.addOffset(6, name_expenseOffset);
          fbb.addOffset(7, amount_expenseOffset);
          fbb.addOffset(8, e_pay_typeOffset);
          fbb.addOffset(9, total_expense_qarzOffset);
          fbb.addOffset(10, total_expense_drawOffset);
          fbb.addBool(11, object.is_synced);
          fbb.addInt64(12, object.add_date?.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final add_dateValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 28);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final id_expenseParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 6);
          final id_add_userParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 8);
          final id_farmer_userParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 10);
          final name_farmerParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12);
          final code_farmerParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 14);
          final name_expenseParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 16);
          final amount_expenseParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 18);
          final e_pay_typeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 20);
          final total_expense_qarzParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 22);
          final total_expense_drawParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 24);
          final is_syncedParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 26, false);
          final add_dateParam = add_dateValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(add_dateValue);
          final object = ExpenseModel(
              id: idParam,
              id_expense: id_expenseParam,
              id_add_user: id_add_userParam,
              id_farmer_user: id_farmer_userParam,
              name_farmer: name_farmerParam,
              code_farmer: code_farmerParam,
              name_expense: name_expenseParam,
              amount_expense: amount_expenseParam,
              e_pay_type: e_pay_typeParam,
              total_expense_qarz: total_expense_qarzParam,
              total_expense_draw: total_expense_drawParam,
              is_synced: is_syncedParam,
              add_date: add_dateParam);

          return object;
        }),
    FarmerProductModel: obx_int.EntityDefinition<FarmerProductModel>(
        model: _entities[3],
        toOneRelations: (FarmerProductModel object) => [],
        toManyRelations: (FarmerProductModel object) => {},
        getId: (FarmerProductModel object) => object.id,
        setId: (FarmerProductModel object, int id) {
          object.id = id;
        },
        objectToFB: (FarmerProductModel object, fb.Builder fbb) {
          final code_farmerOffset = object.code_farmer == null
              ? null
              : fbb.writeString(object.code_farmer!);
          final name_shopOffset = object.name_shop == null
              ? null
              : fbb.writeString(object.name_shop!);
          final name_productOffset = object.name_product == null
              ? null
              : fbb.writeString(object.name_product!);
          final p_pay_typeOffset = object.p_pay_type == null
              ? null
              : fbb.writeString(object.p_pay_type!);
          final p_many_typeOffset = object.p_many_type == null
              ? null
              : fbb.writeString(object.p_many_type!);
          fbb.startTable(19);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.id_product);
          fbb.addInt64(2, object.id_farmer_user);
          fbb.addInt64(3, object.id_add_user);
          fbb.addOffset(4, code_farmerOffset);
          fbb.addOffset(5, name_shopOffset);
          fbb.addOffset(6, name_productOffset);
          fbb.addFloat64(7, object.number_product);
          fbb.addFloat64(8, object.price_product);
          fbb.addFloat64(9, object.total_amount);
          fbb.addOffset(10, p_pay_typeOffset);
          fbb.addOffset(11, p_many_typeOffset);
          fbb.addFloat64(12, object.total_amount_draw_iq);
          fbb.addFloat64(13, object.total_amount_draw_dolar);
          fbb.addFloat64(14, object.total_amount_qarz_iq);
          fbb.addFloat64(15, object.total_amount_qarz_dolar);
          fbb.addBool(16, object.is_synced);
          fbb.addInt64(17, object.add_date?.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final add_dateValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 38);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final id_productParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 6);
          final id_farmer_userParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 8);
          final id_add_userParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 10);
          final code_farmerParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12);
          final name_shopParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 14);
          final name_productParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 16);
          final number_productParam = const fb.Float64Reader()
              .vTableGetNullable(buffer, rootOffset, 18);
          final price_productParam = const fb.Float64Reader()
              .vTableGetNullable(buffer, rootOffset, 20);
          final total_amountParam = const fb.Float64Reader()
              .vTableGetNullable(buffer, rootOffset, 22);
          final p_pay_typeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 24);
          final p_many_typeParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 26);
          final total_amount_draw_iqParam = const fb.Float64Reader()
              .vTableGetNullable(buffer, rootOffset, 28);
          final total_amount_draw_dolarParam = const fb.Float64Reader()
              .vTableGetNullable(buffer, rootOffset, 30);
          final total_amount_qarz_iqParam = const fb.Float64Reader()
              .vTableGetNullable(buffer, rootOffset, 32);
          final total_amount_qarz_dolarParam = const fb.Float64Reader()
              .vTableGetNullable(buffer, rootOffset, 34);
          final is_syncedParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 36, false);
          final add_dateParam = add_dateValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(add_dateValue);
          final object = FarmerProductModel(
              id: idParam,
              id_product: id_productParam,
              id_farmer_user: id_farmer_userParam,
              id_add_user: id_add_userParam,
              code_farmer: code_farmerParam,
              name_shop: name_shopParam,
              name_product: name_productParam,
              number_product: number_productParam,
              price_product: price_productParam,
              total_amount: total_amountParam,
              p_pay_type: p_pay_typeParam,
              p_many_type: p_many_typeParam,
              total_amount_draw_iq: total_amount_draw_iqParam,
              total_amount_draw_dolar: total_amount_draw_dolarParam,
              total_amount_qarz_iq: total_amount_qarz_iqParam,
              total_amount_qarz_dolar: total_amount_qarz_dolarParam,
              is_synced: is_syncedParam,
              add_date: add_dateParam);

          return object;
        }),
    ShopTypeModel: obx_int.EntityDefinition<ShopTypeModel>(
        model: _entities[4],
        toOneRelations: (ShopTypeModel object) => [],
        toManyRelations: (ShopTypeModel object) => {},
        getId: (ShopTypeModel object) => object.id,
        setId: (ShopTypeModel object, int id) {
          object.id = id;
        },
        objectToFB: (ShopTypeModel object, fb.Builder fbb) {
          final t_name_typeOffset = object.t_name_type == null
              ? null
              : fbb.writeString(object.t_name_type!);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.t_id_type);
          fbb.addInt64(2, object.t_id_farmer);
          fbb.addOffset(3, t_name_typeOffset);
          fbb.addBool(4, object.is_synced);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final t_id_typeParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 6);
          final t_id_farmerParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 8);
          final t_name_typeParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10);
          final is_syncedParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 12, false);
          final object = ShopTypeModel(
              id: idParam,
              t_id_type: t_id_typeParam,
              t_id_farmer: t_id_farmerParam,
              t_name_type: t_name_typeParam,
              is_synced: is_syncedParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Driver] entity fields to define ObjectBox queries.
class Driver_ {
  /// See [Driver.id].
  static final id =
      obx.QueryIntegerProperty<Driver>(_entities[0].properties[0]);

  /// See [Driver.d_id_farmer].
  static final d_id_farmer =
      obx.QueryIntegerProperty<Driver>(_entities[0].properties[1]);

  /// See [Driver.id_farmer_user].
  static final id_farmer_user =
      obx.QueryIntegerProperty<Driver>(_entities[0].properties[2]);

  /// See [Driver.id_add_user].
  static final id_add_user =
      obx.QueryIntegerProperty<Driver>(_entities[0].properties[3]);

  /// See [Driver.code_farmer].
  static final code_farmer =
      obx.QueryStringProperty<Driver>(_entities[0].properties[4]);

  /// See [Driver.d_name_farmer].
  static final d_name_farmer =
      obx.QueryStringProperty<Driver>(_entities[0].properties[5]);

  /// See [Driver.d_phone_farmer].
  static final d_phone_farmer =
      obx.QueryStringProperty<Driver>(_entities[0].properties[6]);

  /// See [Driver.add_date].
  static final add_date =
      obx.QueryStringProperty<Driver>(_entities[0].properties[7]);

  /// See [Driver.is_synced].
  static final is_synced =
      obx.QueryBooleanProperty<Driver>(_entities[0].properties[8]);
}

/// [DriverWork] entity fields to define ObjectBox queries.
class DriverWork_ {
  /// See [DriverWork.id].
  static final id =
      obx.QueryIntegerProperty<DriverWork>(_entities[1].properties[0]);

  /// See [DriverWork.d_id_farmer].
  static final d_id_farmer =
      obx.QueryIntegerProperty<DriverWork>(_entities[1].properties[1]);

  /// See [DriverWork.d_name_farmer].
  static final d_name_farmer =
      obx.QueryStringProperty<DriverWork>(_entities[1].properties[2]);

  /// See [DriverWork.type_work].
  static final type_work =
      obx.QueryStringProperty<DriverWork>(_entities[1].properties[3]);

  /// See [DriverWork.name_place_work].
  static final name_place_work =
      obx.QueryStringProperty<DriverWork>(_entities[1].properties[4]);

  /// See [DriverWork.time_work_hours].
  static final time_work_hours =
      obx.QueryStringProperty<DriverWork>(_entities[1].properties[5]);

  /// See [DriverWork.time_work_minutes].
  static final time_work_minutes =
      obx.QueryStringProperty<DriverWork>(_entities[1].properties[6]);

  /// See [DriverWork.count_work].
  static final count_work =
      obx.QueryStringProperty<DriverWork>(_entities[1].properties[7]);

  /// See [DriverWork.price_work].
  static final price_work =
      obx.QueryStringProperty<DriverWork>(_entities[1].properties[8]);

  /// See [DriverWork.pay_type_work].
  static final pay_type_work =
      obx.QueryStringProperty<DriverWork>(_entities[1].properties[9]);

  /// See [DriverWork.is_synced].
  static final is_synced =
      obx.QueryBooleanProperty<DriverWork>(_entities[1].properties[10]);

  /// See [DriverWork.w_id_driver].
  static final w_id_driver =
      obx.QueryIntegerProperty<DriverWork>(_entities[1].properties[11]);
}

/// [ExpenseModel] entity fields to define ObjectBox queries.
class ExpenseModel_ {
  /// See [ExpenseModel.id].
  static final id =
      obx.QueryIntegerProperty<ExpenseModel>(_entities[2].properties[0]);

  /// See [ExpenseModel.id_expense].
  static final id_expense =
      obx.QueryIntegerProperty<ExpenseModel>(_entities[2].properties[1]);

  /// See [ExpenseModel.id_add_user].
  static final id_add_user =
      obx.QueryIntegerProperty<ExpenseModel>(_entities[2].properties[2]);

  /// See [ExpenseModel.id_farmer_user].
  static final id_farmer_user =
      obx.QueryIntegerProperty<ExpenseModel>(_entities[2].properties[3]);

  /// See [ExpenseModel.name_farmer].
  static final name_farmer =
      obx.QueryStringProperty<ExpenseModel>(_entities[2].properties[4]);

  /// See [ExpenseModel.code_farmer].
  static final code_farmer =
      obx.QueryStringProperty<ExpenseModel>(_entities[2].properties[5]);

  /// See [ExpenseModel.name_expense].
  static final name_expense =
      obx.QueryStringProperty<ExpenseModel>(_entities[2].properties[6]);

  /// See [ExpenseModel.amount_expense].
  static final amount_expense =
      obx.QueryStringProperty<ExpenseModel>(_entities[2].properties[7]);

  /// See [ExpenseModel.e_pay_type].
  static final e_pay_type =
      obx.QueryStringProperty<ExpenseModel>(_entities[2].properties[8]);

  /// See [ExpenseModel.total_expense_qarz].
  static final total_expense_qarz =
      obx.QueryStringProperty<ExpenseModel>(_entities[2].properties[9]);

  /// See [ExpenseModel.total_expense_draw].
  static final total_expense_draw =
      obx.QueryStringProperty<ExpenseModel>(_entities[2].properties[10]);

  /// See [ExpenseModel.is_synced].
  static final is_synced =
      obx.QueryBooleanProperty<ExpenseModel>(_entities[2].properties[11]);

  /// See [ExpenseModel.add_date].
  static final add_date =
      obx.QueryDateProperty<ExpenseModel>(_entities[2].properties[12]);
}

/// [FarmerProductModel] entity fields to define ObjectBox queries.
class FarmerProductModel_ {
  /// See [FarmerProductModel.id].
  static final id =
      obx.QueryIntegerProperty<FarmerProductModel>(_entities[3].properties[0]);

  /// See [FarmerProductModel.id_product].
  static final id_product =
      obx.QueryIntegerProperty<FarmerProductModel>(_entities[3].properties[1]);

  /// See [FarmerProductModel.id_farmer_user].
  static final id_farmer_user =
      obx.QueryIntegerProperty<FarmerProductModel>(_entities[3].properties[2]);

  /// See [FarmerProductModel.id_add_user].
  static final id_add_user =
      obx.QueryIntegerProperty<FarmerProductModel>(_entities[3].properties[3]);

  /// See [FarmerProductModel.code_farmer].
  static final code_farmer =
      obx.QueryStringProperty<FarmerProductModel>(_entities[3].properties[4]);

  /// See [FarmerProductModel.name_shop].
  static final name_shop =
      obx.QueryStringProperty<FarmerProductModel>(_entities[3].properties[5]);

  /// See [FarmerProductModel.name_product].
  static final name_product =
      obx.QueryStringProperty<FarmerProductModel>(_entities[3].properties[6]);

  /// See [FarmerProductModel.number_product].
  static final number_product =
      obx.QueryDoubleProperty<FarmerProductModel>(_entities[3].properties[7]);

  /// See [FarmerProductModel.price_product].
  static final price_product =
      obx.QueryDoubleProperty<FarmerProductModel>(_entities[3].properties[8]);

  /// See [FarmerProductModel.total_amount].
  static final total_amount =
      obx.QueryDoubleProperty<FarmerProductModel>(_entities[3].properties[9]);

  /// See [FarmerProductModel.p_pay_type].
  static final p_pay_type =
      obx.QueryStringProperty<FarmerProductModel>(_entities[3].properties[10]);

  /// See [FarmerProductModel.p_many_type].
  static final p_many_type =
      obx.QueryStringProperty<FarmerProductModel>(_entities[3].properties[11]);

  /// See [FarmerProductModel.total_amount_draw_iq].
  static final total_amount_draw_iq =
      obx.QueryDoubleProperty<FarmerProductModel>(_entities[3].properties[12]);

  /// See [FarmerProductModel.total_amount_draw_dolar].
  static final total_amount_draw_dolar =
      obx.QueryDoubleProperty<FarmerProductModel>(_entities[3].properties[13]);

  /// See [FarmerProductModel.total_amount_qarz_iq].
  static final total_amount_qarz_iq =
      obx.QueryDoubleProperty<FarmerProductModel>(_entities[3].properties[14]);

  /// See [FarmerProductModel.total_amount_qarz_dolar].
  static final total_amount_qarz_dolar =
      obx.QueryDoubleProperty<FarmerProductModel>(_entities[3].properties[15]);

  /// See [FarmerProductModel.is_synced].
  static final is_synced =
      obx.QueryBooleanProperty<FarmerProductModel>(_entities[3].properties[16]);

  /// See [FarmerProductModel.add_date].
  static final add_date =
      obx.QueryDateProperty<FarmerProductModel>(_entities[3].properties[17]);
}

/// [ShopTypeModel] entity fields to define ObjectBox queries.
class ShopTypeModel_ {
  /// See [ShopTypeModel.id].
  static final id =
      obx.QueryIntegerProperty<ShopTypeModel>(_entities[4].properties[0]);

  /// See [ShopTypeModel.t_id_type].
  static final t_id_type =
      obx.QueryIntegerProperty<ShopTypeModel>(_entities[4].properties[1]);

  /// See [ShopTypeModel.t_id_farmer].
  static final t_id_farmer =
      obx.QueryIntegerProperty<ShopTypeModel>(_entities[4].properties[2]);

  /// See [ShopTypeModel.t_name_type].
  static final t_name_type =
      obx.QueryStringProperty<ShopTypeModel>(_entities[4].properties[3]);

  /// See [ShopTypeModel.is_synced].
  static final is_synced =
      obx.QueryBooleanProperty<ShopTypeModel>(_entities[4].properties[4]);
}
